/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as KayitOlRouteImport } from './routes/kayit-ol'
import { Route as HaritaRouteImport } from './routes/harita'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitOlRoute = KayitOlRouteImport.update({
  id: '/kayit-ol',
  path: '/kayit-ol',
  getParentRoute: () => rootRouteImport,
} as any)
const HaritaRoute = HaritaRouteImport.update({
  id: '/harita',
  path: '/harita',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/harita': typeof HaritaRoute
  '/kayit-ol': typeof KayitOlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/harita': typeof HaritaRoute
  '/kayit-ol': typeof KayitOlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/harita': typeof HaritaRoute
  '/kayit-ol': typeof KayitOlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/harita' | '/kayit-ol' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/harita' | '/kayit-ol' | '/sitemap.xml'
  id: '__root__' | '/' | '/harita' | '/kayit-ol' | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HaritaRoute: typeof HaritaRoute
  KayitOlRoute: typeof KayitOlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayit-ol': {
      id: '/kayit-ol'
      path: '/kayit-ol'
      fullPath: '/kayit-ol'
      preLoaderRoute: typeof KayitOlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harita': {
      id: '/harita'
      path: '/harita'
      fullPath: '/harita'
      preLoaderRoute: typeof HaritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HaritaRoute: HaritaRoute,
  KayitOlRoute: KayitOlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
