/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MarketFiyatlariRouteImport } from './routes/market-fiyatlari'
import { Route as KayitOlRouteImport } from './routes/kayit-ol'
import { Route as HaritaRouteImport } from './routes/harita'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SaticiUrunlerRouteImport } from './routes/satici.urunler'
import { Route as SaticiProfilRouteImport } from './routes/satici.profil'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicProductImagesSplatRouteImport } from './routes/api/public/product-images.$'
import { Route as ApiPublicHooksSyncMarketPricesRouteImport } from './routes/api/public/hooks/sync-market-prices'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketFiyatlariRoute = MarketFiyatlariRouteImport.update({
  id: '/market-fiyatlari',
  path: '/market-fiyatlari',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitOlRoute = KayitOlRouteImport.update({
  id: '/kayit-ol',
  path: '/kayit-ol',
  getParentRoute: () => rootRouteImport,
} as any)
const HaritaRoute = HaritaRouteImport.update({
  id: '/harita',
  path: '/harita',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SaticiUrunlerRoute = SaticiUrunlerRouteImport.update({
  id: '/satici/urunler',
  path: '/satici/urunler',
  getParentRoute: () => rootRouteImport,
} as any)
const SaticiProfilRoute = SaticiProfilRouteImport.update({
  id: '/satici/profil',
  path: '/satici/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProductImagesSplatRoute =
  ApiPublicProductImagesSplatRouteImport.update({
    id: '/api/public/product-images/$',
    path: '/api/public/product-images/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncMarketPricesRoute =
  ApiPublicHooksSyncMarketPricesRouteImport.update({
    id: '/api/public/hooks/sync-market-prices',
    path: '/api/public/hooks/sync-market-prices',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/harita': typeof HaritaRoute
  '/kayit-ol': typeof KayitOlRoute
  '/market-fiyatlari': typeof MarketFiyatlariRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/satici/profil': typeof SaticiProfilRoute
  '/satici/urunler': typeof SaticiUrunlerRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hooks/sync-market-prices': typeof ApiPublicHooksSyncMarketPricesRoute
  '/api/public/product-images/$': typeof ApiPublicProductImagesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/harita': typeof HaritaRoute
  '/kayit-ol': typeof KayitOlRoute
  '/market-fiyatlari': typeof MarketFiyatlariRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/satici/profil': typeof SaticiProfilRoute
  '/satici/urunler': typeof SaticiUrunlerRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hooks/sync-market-prices': typeof ApiPublicHooksSyncMarketPricesRoute
  '/api/public/product-images/$': typeof ApiPublicProductImagesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/harita': typeof HaritaRoute
  '/kayit-ol': typeof KayitOlRoute
  '/market-fiyatlari': typeof MarketFiyatlariRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/satici/profil': typeof SaticiProfilRoute
  '/satici/urunler': typeof SaticiUrunlerRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hooks/sync-market-prices': typeof ApiPublicHooksSyncMarketPricesRoute
  '/api/public/product-images/$': typeof ApiPublicProductImagesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/giris'
    | '/harita'
    | '/kayit-ol'
    | '/market-fiyatlari'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/satici/profil'
    | '/satici/urunler'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hooks/sync-market-prices'
    | '/api/public/product-images/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/giris'
    | '/harita'
    | '/kayit-ol'
    | '/market-fiyatlari'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/satici/profil'
    | '/satici/urunler'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hooks/sync-market-prices'
    | '/api/public/product-images/$'
  id:
    | '__root__'
    | '/'
    | '/giris'
    | '/harita'
    | '/kayit-ol'
    | '/market-fiyatlari'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/satici/profil'
    | '/satici/urunler'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hooks/sync-market-prices'
    | '/api/public/product-images/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GirisRoute: typeof GirisRoute
  HaritaRoute: typeof HaritaRoute
  KayitOlRoute: typeof KayitOlRoute
  MarketFiyatlariRoute: typeof MarketFiyatlariRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  SaticiProfilRoute: typeof SaticiProfilRoute
  SaticiUrunlerRoute: typeof SaticiUrunlerRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksSyncMarketPricesRoute: typeof ApiPublicHooksSyncMarketPricesRoute
  ApiPublicProductImagesSplatRoute: typeof ApiPublicProductImagesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-fiyatlari': {
      id: '/market-fiyatlari'
      path: '/market-fiyatlari'
      fullPath: '/market-fiyatlari'
      preLoaderRoute: typeof MarketFiyatlariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayit-ol': {
      id: '/kayit-ol'
      path: '/kayit-ol'
      fullPath: '/kayit-ol'
      preLoaderRoute: typeof KayitOlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harita': {
      id: '/harita'
      path: '/harita'
      fullPath: '/harita'
      preLoaderRoute: typeof HaritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satici/urunler': {
      id: '/satici/urunler'
      path: '/satici/urunler'
      fullPath: '/satici/urunler'
      preLoaderRoute: typeof SaticiUrunlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satici/profil': {
      id: '/satici/profil'
      path: '/satici/profil'
      fullPath: '/satici/profil'
      preLoaderRoute: typeof SaticiProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/product-images/$': {
      id: '/api/public/product-images/$'
      path: '/api/public/product-images/$'
      fullPath: '/api/public/product-images/$'
      preLoaderRoute: typeof ApiPublicProductImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-market-prices': {
      id: '/api/public/hooks/sync-market-prices'
      path: '/api/public/hooks/sync-market-prices'
      fullPath: '/api/public/hooks/sync-market-prices'
      preLoaderRoute: typeof ApiPublicHooksSyncMarketPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GirisRoute: GirisRoute,
  HaritaRoute: HaritaRoute,
  KayitOlRoute: KayitOlRoute,
  MarketFiyatlariRoute: MarketFiyatlariRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  SaticiProfilRoute: SaticiProfilRoute,
  SaticiUrunlerRoute: SaticiUrunlerRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksSyncMarketPricesRoute: ApiPublicHooksSyncMarketPricesRoute,
  ApiPublicProductImagesSplatRoute: ApiPublicProductImagesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
